/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ApButton {
        "color"?: string;
        "content": string;
        "type"?: string;
    }
}
export interface ApButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLApButtonElement;
}
declare global {
    interface HTMLApButtonElement extends Components.ApButton, HTMLStencilElement {
    }
    var HTMLApButtonElement: {
        prototype: HTMLApButtonElement;
        new (): HTMLApButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ap-button": HTMLApButtonElement;
    }
}
declare namespace LocalJSX {
    interface ApButton {
        "color"?: string;
        "content"?: string;
        "onClickedButton"?: (event: ApButtonCustomEvent<any>) => void;
        "type"?: string;
    }
    interface IntrinsicElements {
        "ap-button": ApButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ap-button": LocalJSX.ApButton & JSXBase.HTMLAttributes<HTMLApButtonElement>;
        }
    }
}
